name: Run CRE tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build & Run tests
    steps:
      - uses: actions/checkout@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # omit version, uses version of packageManager in package.json
      - name: Install
        run: pnpm install
      - name: Run Tests
        run: pnpm run test --watch=all
        env: # We should set CI=true so the app doesn't ask for user input
          CI: true
